### ISSUE TITLE
I get an error like this when i want to use mindflow

### ISSUE THREAD

**Issue by TarikKaanKoc** [mindflowai/mindflow#117]
### I think there is a conflict because of the env ?

```
Traceback (most recent call last):
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libopenblas.dylib'
  Referenced from: '/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
  Reason: tried: '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/bin/../lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/bin/../lib/libopenblas.dylib' (no such file), '/usr/local/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/koc/opt/anaconda3/bin/mf", line 5, in <module>
    from mindflow.cli.new_click_cli.cli_main import mindflow_cli
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/mindflow/cli/new_click_cli/cli_main.py", line 5, in <module>
    from mindflow.cli.new_click_cli.commands.git.commit import commit
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/mindflow/cli/new_click_cli/commands/git/commit.py", line 6, in <module>
    from mindflow.core.git.commit import run_commit
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/mindflow/core/git/commit.py", line 4, in <module>
    from mindflow.core.git.diff import run_diff
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/mindflow/core/git/diff.py", line 10, in <module>
    from mindflow.db.objects.model import ConfiguredModel
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/mindflow/db/objects/model.py", line 4, in <module>
    import numpy as np
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Users/koc/opt/anaconda3/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libopenblas.dylib'
  Referenced from: '/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
  Reason: tried: '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/python3.9/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/bin/../lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/lib/libopenblas.dylib' (no such file), '/Users/koc/opt/anaconda3/bin/../lib/libopenblas.dylib' (no such file), '/usr/local/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file)
```

**Comment by steegecs** [comment]
Hi Tarik! Which command are you running when you got this error?

**Comment by steegecs** [comment]
Have you tried creating a new environment with conda?

**Comment by TarikKaanKoc** [comment]
I solved the problem. As I suspected, it was a conflict issue related to conda environment. @steegecs
